// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cockpit-v3/CockpitV3.tsx": () => import("../components/mockups/cockpit-v3/CockpitV3.tsx")
};
